name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Clean build artifacts
        run: |
          rm -rf build dist *.egg-info


      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Set up .pypirc for GitHub Packages
        run: |
          mkdir -p ~/.config/pypoetry
          echo "[distutils]" > ~/.pypirc
          echo "index-servers =" >> ~/.pypirc
          echo "    pypi" >> ~/.pypirc
          echo "    github" >> ~/.pypirc
          echo "" >> ~/.pypirc
          echo "[pypi]" >> ~/.pypirc
          echo "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
          echo "username: __token__" >> ~/.pypirc
          echo "password: ${{ secrets.PYPI_API_TOKEN }}" >> ~/.pypirc
          echo "" >> ~/.pypirc
          echo "[github]" >> ~/.pypirc
          echo "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
          echo "username: ${{ github.actor }}" >> ~/.pypirc
          echo "password: ${{ secrets.GITHUB_TOKEN }}" >> ~/.pypirc


      - name: Configure .pypirc for PyPI and GitHub Packages
        run: |
          echo "[distutils]" > ~/.pypirc
          echo "index-servers =" >> ~/.pypirc
          echo "    pypi" >> ~/.pypirc
          echo "    github" >> ~/.pypirc
      
          echo "[pypi]" >> ~/.pypirc
          echo "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
          echo "username: __token__" >> ~/.pypirc
          echo "password: ${{ secrets.PYPI_API_TOKEN }}" >> ~/.pypirc
      
          echo "[github]" >> ~/.pypirc
          echo "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
          echo "username: ${{ github.actor }}" >> ~/.pypirc
          echo "password: ${{ secrets.GITHUB_TOKEN }}" >> ~/.pypirc


      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install twine
          twine upload dist/*

      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*


