name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Clean build artifacts
        run: rm -rf build dist *.egg-info

      - name: Build Package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          twine upload \
            --repository-url https://pypi.pkg.github.com/kmukoo101 \
            dist/*
